# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be2abbfaab85d6ac09694dd488eca256761c185114ea88ab86d437e89f77e8dd6dee618c03d0853e5f0f358b5a18e2a844d19b52270366d1a74002921b693e49

test:
  secret_key_base: f074a7e959ecd0f8eae4872a5b5a82e9cbcd541c0f34797a9fd281ce56958e6d3caaa9f86e4296e3b8f2707fbf653ce9955d1a3f97da6bc270eb8d7c93afab84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
